kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  ENV:  "{{ .Values.configmap.env.name }}"
  HOST: "{{ .Values.configmap.env.host }}"
  PORT: "{{ .Values.configmap.env.targetPort }}"
