apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.svcName }}-{{ .Values.configmap.env.name }}"
  namespace: {{ .Values.namespace }}
  labels:
    serviceName: "{{ .Values.svcName }}-{{ .Values.configmap.env.name }}"
spec:
  minReplicas: {{ .Values.scalingReplicas.minReplica }}
  maxReplicas: {{ .Values.scalingReplicas.maxReplica }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.svcName }}-{{ .Values.configmap.env.name }}"
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90